[workspace.package]
version = "0.1.0"
edition = "2021"
license = "(MIT OR Apache-2.0) AND Unicode-3.0"

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
fuscum = { path = "crates/fuscum" }

[workspace.metadata.crane]
name = "fuscum"
