[package]
name = "fuscum"
version = "0.1.0"
edition = "2021"

[dependencies]
ast-grep-core = "0.32.2"
ast-grep-language = "0.32.2"
clap = { version = "4.5.23", features = ["derive"] }
rayon = "1.10.0"
walkdir = "2.5.0"

[dev-dependencies]
insta = "1.41.1"

