[package]
name = "fuscum"
version = "0.1.0"
edition = "2021"
license = "(MIT OR Apache-2.0) AND Unicode-3.0"

[dependencies]
ast-grep-core = "0.32.2"
ast-grep-language = "0.32.2"
typed-builder = "0.20.0"

[dev-dependencies]
insta = "1.41.1"

