[package]
name = "fuscum"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ast-grep-core = "0.32.2"
ast-grep-language = "0.32.2"
typed-builder = "0.20.0"

[dev-dependencies]
insta = "1.41.1"